### ISSUE TITLE
Add pyproject toml support

### ISSUE THREAD

**Issue by Hoxbro** [Hoxbro/clean_notebook#23]
It could be nice to define settings for files in the `pyproject.toml`, thinking about something like this:

``` toml
[tool.notebook-clean]
keep_empty = true
dryrun = true

[tool.notebook-clean.per-file-ignores]
"tests/**/*" = ["slideshow", "tags"]
```
